[build]
builder = "nixpacks"
buildCommand = """
#!/bin/bash
echo "Installing FFmpeg..."
mkdir -p /tmp/ffmpeg
cd /tmp/ffmpeg
curl -L https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz -o ffmpeg.tar.xz
tar -xf ffmpeg.tar.xz --strip-components=1
cp bin/ffmpeg /usr/local/bin/
chmod +x /usr/local/bin/ffmpeg
cd /
rm -rf /tmp/ffmpeg
echo "FFmpeg installation complete:"
ffmpeg -version
"""

[deploy]
startCommand = "python tunecast.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"
