[build]
builder = "nixpacks"
buildCommand = '''
  echo "Installing static ffmpeg build..."
  curl -L https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz -o ffmpeg.tar.xz &&
  tar -xf ffmpeg.tar.xz &&
  cp ffmpeg-*-static/ffmpeg /usr/bin/ffmpeg &&
  chmod +x /usr/bin/ffmpeg &&
  echo "ffmpeg installed:" &&
  ffmpeg -version
'''

[deploy]
preDeployCommand = []
startCommand = "python tunecast.py"  # Adjust this if your bot entry file is different
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"
